### ISSUE TITLE
“Doña Quixote”, not “Dawn Quixote”

### ISSUE THREAD

**Issue by vitorgalvao** [Garrett-R/gender_bender#4]
“Don” [is a honorific](https://en.wikipedia.org/wiki/Don_(honorific)), not a name. The correct equivalent is “Doña”.

**Comment by vitorgalvao** [comment]
I see [someone else made the same comment on HN](https://news.ycombinator.com/item?id=17748060) and [you did it on purpose](https://news.ycombinator.com/item?id=17748084).

**Comment by Garrett-R** [comment]
Well, if 2 people noticed, clearly it was not a good one, better to translate properly, just updated.  

In terms of default translation, I'm going to keep "Don" -> "Dawn" for now.  Basically, it would be really hard to tell from context between the honorific and the name, at least with 100% accuracy.

Thanks!
